# Copyright 2026 NDC Digital, LLC
# SPDX-License-Identifier: Apache-2.0

"""Flametrench v0.1 conformance suite — Python harness for identity.

Exercises verify_password against the cross-language Argon2id parity
fixture vendored from
github.com/flametrench/spec/conformance/fixtures/identity/.

Why this fixture matters: the fixture's PHC hash was generated by the
Node ``argon2`` package. Python's ``argon2-cffi`` (which wraps the
reference Argon2 C library) MUST accept it. If this test fails,
password-based auth has become non-portable across SDKs — a regression
Flametrench exists to prevent.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from flametrench_identity import verify_password_hash

_FIXTURES_DIR = Path(__file__).parent / "conformance" / "fixtures"


def _load_fixture(relative_path: str) -> dict[str, Any]:
    raw = (_FIXTURES_DIR / relative_path).read_text(encoding="utf-8")
    return json.loads(raw)


def _params(relative_path: str) -> list[Any]:
    fixture = _load_fixture(relative_path)
    return [pytest.param(t, id=t["id"]) for t in fixture["tests"]]


@pytest.mark.parametrize("test_case", _params("identity/argon2id.json"))
def test_verify_password_conformance(test_case: dict[str, Any]) -> None:
    inp = test_case["input"]
    expected = test_case["expected"]["result"]
    result = verify_password_hash(inp["phc_hash"], inp["candidate_password"])
    assert result is expected
