# Copyright 2026 NDC Digital, LLC
# SPDX-License-Identifier: Apache-2.0

"""Flametrench v0.1 conformance suite — Python harness for identity.

Exercises verify_password against the cross-language Argon2id parity
fixture vendored from
github.com/flametrench/spec/conformance/fixtures/identity/.

Why this fixture matters: the fixture's PHC hash was generated by the
Node ``argon2`` package. Python's ``argon2-cffi`` (which wraps the
reference Argon2 C library) MUST accept it. If this test fails,
password-based auth has become non-portable across SDKs — a regression
Flametrench exists to prevent.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from flametrench_identity import (
    classify_bearer,
    is_structurally_valid_pat_token,
    verify_password_hash,
)

_FIXTURES_DIR = Path(__file__).parent / "conformance" / "fixtures"


def _load_fixture(relative_path: str) -> dict[str, Any]:
    raw = (_FIXTURES_DIR / relative_path).read_text(encoding="utf-8")
    return json.loads(raw)


def _params(relative_path: str) -> list[Any]:
    fixture = _load_fixture(relative_path)
    return [pytest.param(t, id=t["id"]) for t in fixture["tests"]]


@pytest.mark.parametrize("test_case", _params("identity/argon2id.json"))
def test_verify_password_conformance(test_case: dict[str, Any]) -> None:
    inp = test_case["input"]
    expected = test_case["expected"]["result"]
    result = verify_password_hash(inp["phc_hash"], inp["candidate_password"])
    assert result is expected


# v0.3 — security-audit-v0.3.md M5: every SDK consumes the PAT fixtures.


@pytest.mark.parametrize("test_case", _params("identity/pat/token-format.json"))
def test_pat_token_format_conformance(test_case: dict[str, Any]) -> None:
    """ADR 0016 §"Wire format" — structural validation MUST classify
    every fixture token identically across SDKs."""
    assert (
        is_structurally_valid_pat_token(test_case["input"]["token"])
        is test_case["expected"]["result"]
    )


@pytest.mark.parametrize("test_case", _params("identity/pat/bearer-prefix-routing.json"))
def test_pat_bearer_routing_conformance(test_case: dict[str, Any]) -> None:
    """ADR 0016 §"Bearer routing" — the auth.kind classifier MUST agree
    across SDKs on every fixture token."""
    assert (
        classify_bearer(test_case["input"]["token"])
        == test_case["expected"]["result"]
    )
