# Copyright 2026 NDC Digital, LLC
# SPDX-License-Identifier: Apache-2.0

"""flametrench-identity — users, credentials, and user-bound sessions.

The spec-normative identity layer for Flametrench v0.1. See the upstream
specification at
https://github.com/flametrench/spec/blob/main/docs/identity.md.

Argon2id is pinned at the OWASP floor (m=19456 KiB, t=2, p=1). PHC-encoded
hashes produced by this SDK verify identically under the Node and PHP
SDKs — the conformance suite proves it mechanically.
"""

from .errors import (
    AlreadyTerminalError,
    CredentialNotActiveError,
    CredentialTypeMismatchError,
    DuplicateCredentialError,
    IdentityError,
    InvalidCredentialError,
    InvalidTokenError,
    NotFoundError,
    PreconditionError,
    SessionExpiredError,
)
from .hashing import hash_password, verify_password_hash
from .in_memory import InMemoryIdentityStore
from .mfa import (
    DEFAULT_TOTP_ALGORITHM,
    DEFAULT_TOTP_DIGITS,
    DEFAULT_TOTP_PERIOD,
    Factor,
    FactorStatus,
    FactorType,
    MfaProof,
    MfaVerifyResult,
    RECOVERY_CODE_COUNT,
    RECOVERY_CODE_LENGTH,
    RecoveryEnrollmentResult,
    RecoveryFactor,
    RecoveryProof,
    TotpEnrollmentResult,
    TotpFactor,
    TotpProof,
    UserMfaPolicy,
    WebAuthnEnrollmentResult,
    WebAuthnFactor,
    WebAuthnProof,
    generate_recovery_code,
    generate_recovery_codes,
    generate_totp_secret,
    is_valid_recovery_code,
    normalize_recovery_input,
    totp_compute,
    totp_otpauth_uri,
    totp_verify,
)
from .store import IdentityStore
from .webauthn import (
    WebAuthnAssertionResult,
    WebAuthnChallengeMismatchError,
    WebAuthnCounterRegressionError,
    WebAuthnError,
    WebAuthnMalformedError,
    WebAuthnOriginMismatchError,
    WebAuthnRpIdMismatchError,
    WebAuthnSignatureError,
    WebAuthnTypeMismatchError,
    WebAuthnUnsupportedKeyError,
    WebAuthnUserNotPresentError,
    WebAuthnUserNotVerifiedError,
    cose_key_es256,
    webauthn_verify_assertion,
)
from .types import (
    ARGON2ID_FLOOR,
    Credential,
    CredentialType,
    OidcCredential,
    Page,
    PasskeyCredential,
    PasswordCredential,
    Session,
    SessionWithToken,
    Status,
    User,
    VerifiedCredential,
)

__all__ = [
    "ARGON2ID_FLOOR",
    "AlreadyTerminalError",
    "Credential",
    "CredentialNotActiveError",
    "CredentialType",
    "CredentialTypeMismatchError",
    "DEFAULT_TOTP_ALGORITHM",
    "DEFAULT_TOTP_DIGITS",
    "DEFAULT_TOTP_PERIOD",
    "DuplicateCredentialError",
    "Factor",
    "FactorStatus",
    "FactorType",
    "MfaProof",
    "MfaVerifyResult",
    "IdentityError",
    "IdentityStore",
    "InMemoryIdentityStore",
    "InvalidCredentialError",
    "InvalidTokenError",
    "NotFoundError",
    "OidcCredential",
    "Page",
    "PasskeyCredential",
    "PasswordCredential",
    "PreconditionError",
    "RECOVERY_CODE_COUNT",
    "RECOVERY_CODE_LENGTH",
    "RecoveryEnrollmentResult",
    "RecoveryFactor",
    "RecoveryProof",
    "TotpEnrollmentResult",
    "Session",
    "SessionExpiredError",
    "SessionWithToken",
    "Status",
    "TotpFactor",
    "TotpProof",
    "User",
    "UserMfaPolicy",
    "VerifiedCredential",
    "WebAuthnAssertionResult",
    "WebAuthnChallengeMismatchError",
    "WebAuthnCounterRegressionError",
    "WebAuthnEnrollmentResult",
    "WebAuthnError",
    "WebAuthnFactor",
    "WebAuthnProof",
    "WebAuthnMalformedError",
    "WebAuthnOriginMismatchError",
    "WebAuthnRpIdMismatchError",
    "WebAuthnSignatureError",
    "WebAuthnTypeMismatchError",
    "WebAuthnUnsupportedKeyError",
    "WebAuthnUserNotPresentError",
    "WebAuthnUserNotVerifiedError",
    "cose_key_es256",
    "generate_recovery_code",
    "generate_recovery_codes",
    "generate_totp_secret",
    "hash_password",
    "is_valid_recovery_code",
    "normalize_recovery_input",
    "totp_compute",
    "totp_otpauth_uri",
    "totp_verify",
    "verify_password_hash",
    "webauthn_verify_assertion",
]

__version__ = "0.1.0"
